# Generated by Django 3.1.5 on 2021-02-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub',
            field=models.CharField(default='Tata McGraw Hill', max_length=250),
        ),
    ]
