# Generated by Django 2.1.3 on 2021-05-02 05:25

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0003_book_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
